name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate GitHub contribution snake
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: DiegoMoraes-Coding
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
